<a href="https://colab.research.google.com/github/alanfmorato/Estrutura-de-Dados/blob/main/ED.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

df = pd.read_csv('/content/perfil_eleitor_secao_ATUAL_AM.csv',
                 sep=";", on_bad_lines = 'skip', encoding='Latin 1')

df2 = pd.read_csv('/content/bweb_1t_AM_051020221321.csv',
                 sep=";", on_bad_lines = 'skip', encoding='Latin 1')

#01 Jornalista quer saber a classificação do eleitorado a partir do estado civil, escolaridade e faixa etária, além da quantidade de eleitores que utilizam nome social

In [2]:
FaixaEtaria = df.groupby(['DS_FAIXA_ETARIA'])['QT_ELEITORES_PERFIL'].sum()
FaixaEtaria

DS_FAIXA_ETARIA
100 anos ou mais       558
15 anos                538
16 anos              12632
17 anos              35779
18 anos              53756
19 anos              62354
20 anos              65141
21 a 24 anos        277512
25 a 29 anos        350304
30 a 34 anos        311750
35 a 39 anos        293642
40 a 44 anos        290848
45 a 49 anos        256719
50 a 54 anos        204783
55 a 59 anos        166372
60 a 64 anos        136914
65 a 69 anos        104311
70 a 74 anos         71571
75 a 79 anos         42603
80 a 84 anos         21425
85 a 89 anos          9820
90 a 94 anos          3407
95 a 99 anos          1084
Inválida                 8
Name: QT_ELEITORES_PERFIL, dtype: int64

In [3]:
escolaridade = df.groupby(['DS_GRAU_ESCOLARIDADE'])['QT_ELEITORES_PERFIL'].sum()
escolaridade

DS_GRAU_ESCOLARIDADE
ANALFABETO                       103401
ENSINO FUNDAMENTAL COMPLETO      125927
ENSINO FUNDAMENTAL INCOMPLETO    529469
ENSINO MÉDIO COMPLETO            904933
ENSINO MÉDIO INCOMPLETO          544815
LÊ E ESCREVE                     146966
SUPERIOR COMPLETO                244658
SUPERIOR INCOMPLETO              173662
Name: QT_ELEITORES_PERFIL, dtype: int64

In [4]:
estadocivil = df.groupby(['DS_ESTADO_CIVIL'])['QT_ELEITORES_PERFIL'].sum()
estadocivil

DS_ESTADO_CIVIL
CASADO                     569941
DIVORCIADO                  53927
NÃO INFORMADO                   2
SEPARADO JUDICIALMENTE      11471
SOLTEIRO                  2098461
VIÚVO                       40029
Name: QT_ELEITORES_PERFIL, dtype: int64

#Jornalista quer saber, daquela região, a cidade com mais eleitores jovem e mais eleitores idosos

In [5]:
jovens = {}
for zona in df.NR_ZONA.unique():
    result = df.query('NR_ZONA == @zona').groupby('DS_FAIXA_ETARIA')['QT_ELEITORES_PERFIL'].sum()
    jovens[zona] = result[1:8].sum()
for zona in sorted(jovens, key=lambda x:jovens[x], reverse = True):
    print (f'Zona eleitoral {zona}: {jovens[zona]}')

Zona eleitoral 62: 26349
Zona eleitoral 65: 24215
Zona eleitoral 63: 23411
Zona eleitoral 68: 20932
Zona eleitoral 70: 20241
Zona eleitoral 6: 19421
Zona eleitoral 59: 17470
Zona eleitoral 3: 17330
Zona eleitoral 40: 17157
Zona eleitoral 58: 17140
Zona eleitoral 32: 16353
Zona eleitoral 4: 15984
Zona eleitoral 31: 14879
Zona eleitoral 37: 12968
Zona eleitoral 23: 12635
Zona eleitoral 5: 11711
Zona eleitoral 2: 11467
Zona eleitoral 9: 11452
Zona eleitoral 35: 11165
Zona eleitoral 8: 10904
Zona eleitoral 17: 10693
Zona eleitoral 1: 10507
Zona eleitoral 36: 8499
Zona eleitoral 56: 8457
Zona eleitoral 47: 7666
Zona eleitoral 16: 7194
Zona eleitoral 22: 7105
Zona eleitoral 24: 6732
Zona eleitoral 19: 6477
Zona eleitoral 45: 6168
Zona eleitoral 12: 5946
Zona eleitoral 60: 5687
Zona eleitoral 11: 5621
Zona eleitoral 15: 5385
Zona eleitoral 20: 5287
Zona eleitoral 26: 5106
Zona eleitoral 51: 4902
Zona eleitoral 21: 4824
Zona eleitoral 29: 4809
Zona eleitoral 14: 4681
Zona eleitoral 27: 4359
Zona eleitoral 41: 4193
Zona eleitoral 10: 4109
Zona eleitoral 54: 3802
Zona eleitoral 7: 3801
Zona eleitoral 33: 3652
Zona eleitoral 43: 3523
Zona eleitoral 38: 3432
Zona eleitoral 13: 3369
Zona eleitoral 67: 3246
Zona eleitoral 50: 3037
Zona eleitoral 44: 2955
Zona eleitoral 18: 2733
Zona eleitoral 49: 2706
Zona eleitoral 34: 2685
Zona eleitoral 42: 2503
Zona eleitoral 46: 2388
Zona eleitoral 30: 2083
Zona eleitoral 69: 2016
Zona eleitoral 48: 1518

In [6]:
idosos = {}
for zona in df.NR_ZONA.unique():
    result = df.query('NR_ZONA == @zona').groupby('DS_FAIXA_ETARIA')['QT_ELEITORES_PERFIL'].sum()
    idosos[zona] = result[14:22].sum() + int(result[0])
for zona in sorted(idosos, key=lambda x:idosos[x], reverse = True):
    print (f'Zona eleitoral {zona}: {idosos[zona]}')

<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])

Zona eleitoral 1: 30687
Zona eleitoral 40: 29892
Zona eleitoral 32: 27655
Zona eleitoral 58: 25516
Zona eleitoral 62: 24647
Zona eleitoral 2: 24234
Zona eleitoral 63: 23195
Zona eleitoral 37: 22959
Zona eleitoral 31: 22914
Zona eleitoral 68: 21322
Zona eleitoral 65: 21213
Zona eleitoral 59: 20429
Zona eleitoral 70: 20427
Zona eleitoral 6: 19550
Zona eleitoral 3: 18563
Zona eleitoral 4: 14508
Zona eleitoral 35: 10664
Zona eleitoral 5: 10117
Zona eleitoral 56: 9698
Zona eleitoral 8: 9616
Zona eleitoral 9: 8297
Zona eleitoral 23: 7691
Zona eleitoral 36: 7236
Zona eleitoral 19: 6745
Zona eleitoral 51: 6629
Zona eleitoral 16: 6322
Zona eleitoral 12: 5308
Zona eleitoral 47: 4667
Zona eleitoral 22: 4568
Zona eleitoral 14: 4457
Zona eleitoral 15: 4445
Zona eleitoral 17: 4377
Zona eleitoral 20: 4315
Zona eleitoral 11: 4148
Zona eleitoral 27: 3919
Zona eleitoral 26: 3885
Zona eleitoral 45: 3801
Zona eleitoral 21: 3698
Zona eleitoral 60: 3293
Zona eleitoral 7: 3272
Zona eleitoral 43: 3095
Zona eleitoral 10: 2874
Zona eleitoral 34: 2812
Zona eleitoral 24: 2607
Zona eleitoral 18: 2492
Zona eleitoral 54: 2464
Zona eleitoral 38: 2345
Zona eleitoral 41: 2267
Zona eleitoral 44: 2048
Zona eleitoral 67: 2024
Zona eleitoral 46: 1820
Zona eleitoral 29: 1806
Zona eleitoral 30: 1698
Zona eleitoral 13: 1630
Zona eleitoral 49: 1439
Zona eleitoral 33: 1438
Zona eleitoral 42: 1427
Zona eleitoral 69: 1110
Zona eleitoral 48: 828
Zona eleitoral 50: 823

<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])
<ipython-input-6-523d28d7cba9>:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  idosos[zona] = result[14:22].sum() + int(result[0])

#Jornalista quer poder relacionar características do eleitorado de acordo com o representante eleito em determinada região de eleições futuras

In [7]:
df2.groupby('NM_VOTAVEL')['QT_VOTOS'].sum().sort_values(ascending = False)

NM_VOTAVEL
LULA                  1019684
JAIR BOLSONARO         880198
WILSON LIMA            819784
OMAR AZIZ              784007
CORONEL MENEZES        737875
                       ...
ELOIZA HELENA               4
MEIRE MAIA                  4
ROBERTO DOS SANTOS          3
LUZIMARA RAMOS              2
NÚBIA PANTOJA               1
Name: QT_VOTOS, Length: 632, dtype: int64

In [8]:
votacao = {}
for zona in df2.NR_ZONA.unique():
    result = df2.query('NR_ZONA == @zona').groupby('NM_VOTAVEL')['QT_VOTOS'].sum()
    total = sum(result)
    votacao[zona] = {'Jair Bolsonaro': round(result["JAIR BOLSONARO"] / total * 100, 1),
                     'Lula': round(result["LULA"] / total * 100, 1),
                     'Simone Tebet': round(result['SIMONE TEBET'] / total * 100, 1),
                     'Nulos':round(result['Nulo'] / total * 100, 1),
                     'Brancos':round(result['Branco'] / total * 100, 1)
                    }
votacao = pd.DataFrame(votacao).transpose()
votacao

    Jair Bolsonaro  Lula  Simone Tebet  Nulos  Brancos
1             10.4   7.0           1.2    4.1      3.6
2             11.1   6.2           1.2    3.6      3.3
3              5.8  12.7           0.7    3.0      1.4
4              2.9  15.7           0.7    2.8      2.0
5              2.5  16.5           0.3    3.3      1.1
6              7.6  11.0           0.6    3.2      1.3
7              7.3  11.6           0.4    3.4      0.6
8              7.1  11.4           0.6    3.4      1.7
9              6.5  12.3           0.5    3.0      1.3
10             4.2  14.6           0.5    3.9      0.9
11             4.5  13.8           0.7    4.5      1.4
12             6.0  12.5           0.6    3.8      1.0
13             7.6  10.9           0.5    3.8      1.3
14             9.4   8.9           0.5    5.5      2.6
15             3.9  15.0           0.4    3.6      0.7
16             6.1  12.6           0.6    3.0      1.1
17             8.1  10.3           0.7    3.7      2.8
18             6.1  12.4           0.6    4.0      0.8
19             3.5  15.6           0.4    3.6      1.1
20             2.8  16.1           0.4    3.4      0.8
21             3.8  14.5           0.8    3.4      1.0
22             3.1  15.5           0.5    4.3      0.7
23             6.0  12.4           0.7    4.3      1.3
24             5.4  13.6           0.4    3.0      1.0
26             1.4  17.6           0.4    3.6      0.8
27             5.6  13.0           0.6    3.3      1.2
29             4.3  14.4           0.5    4.1      0.9
30             4.5  13.7           0.6    5.0      1.3
31             9.5   8.2           0.9    4.7      3.6
32            10.4   7.2           1.1    4.1      3.6
33             7.5  11.2           0.8    2.5      0.7
34             8.3  10.2           0.7    3.3      1.1
35             5.2  13.5           0.5    3.8      0.9
36             5.7  12.7           0.8    4.2      1.5
37            10.3   7.0           1.1    4.5      4.0
38             8.7   9.8           0.6    4.1      0.6
40            10.8   6.7           1.1    4.0      3.5
41             4.4  13.6           1.0    5.7      1.2
42             3.4  15.3           0.5    3.8      0.6
43             2.6  16.6           0.3    3.0      0.9
44             5.3  13.5           0.3    4.1      0.7
45             7.9  10.1           0.8    5.3      1.6
46             4.4  13.4           0.9    4.4      0.8
47             4.1  14.7           0.5    4.0      0.7
48             6.8  11.0           1.3    3.6      1.0
49             5.1  13.8           0.5    3.8      0.7
50             6.4  11.3           1.0    4.7      0.9
51             8.1  10.1           0.7    3.8      2.4
54             6.6  12.3           0.3    3.2      0.6
56             7.7  10.6           0.8    3.4      2.1
58            10.8   6.7           1.0    4.2      4.1
59             9.9   7.7           0.9    4.9      4.4
60             5.0  13.5           0.8    3.4      0.7
62            10.4   7.2           0.9    4.2      4.0
63            10.1   7.6           0.9    4.7      4.3
65            10.3   7.4           0.9    4.4      4.4
67            11.6   7.3           0.4    3.6      2.8
68             9.5   8.4           0.8    4.7      3.9
69             4.4  14.2           0.5    4.9      0.7
70            10.3   7.2           0.9    4.8      4.4

#Jornalista quer saber a percentagem de eleitores ausentes da última eleição

In [9]:
print (f"Porcentagem de comparecimento {100 - (df2['QT_COMPARECIMENTO'].sum()/df2['QT_APTOS'].sum()*100):.2f}%")

Porcentagem de comparecimento 18.47%

#Jornalista quer saber a evolução do número de eleitores

In [10]:
df2.columns

Index(['DT_GERACAO', 'HH_GERACAO', 'ANO_ELEICAO', 'CD_TIPO_ELEICAO',
       'NM_TIPO_ELEICAO', 'CD_PLEITO', 'DT_PLEITO', 'NR_TURNO', 'CD_ELEICAO',
       'DS_ELEICAO', 'SG_UF', 'CD_MUNICIPIO', 'NM_MUNICIPIO', 'NR_ZONA',
       'NR_SECAO', 'NR_LOCAL_VOTACAO', 'CD_CARGO_PERGUNTA',
       'DS_CARGO_PERGUNTA', 'NR_PARTIDO', 'SG_PARTIDO', 'NM_PARTIDO',
       'DT_BU_RECEBIDO', 'QT_APTOS', 'QT_COMPARECIMENTO', 'QT_ABSTENCOES',
       'CD_TIPO_URNA', 'DS_TIPO_URNA', 'CD_TIPO_VOTAVEL', 'DS_TIPO_VOTAVEL',
       'NR_VOTAVEL', 'NM_VOTAVEL', 'QT_VOTOS', 'NR_URNA_EFETIVADA',
       'CD_CARGA_1_URNA_EFETIVADA', 'CD_CARGA_2_URNA_EFETIVADA',
       'CD_FLASHCARD_URNA_EFETIVADA', 'DT_CARGA_URNA_EFETIVADA',
       'DS_CARGO_PERGUNTA_SECAO', 'DS_AGREGADAS', 'DT_ABERTURA',
       'DT_ENCERRAMENTO', 'QT_ELEITORES_BIOMETRIA_NH', 'DT_EMISSAO_BU',
       'NR_JUNTA_APURADORA', 'NR_TURMA_APURADORA'],
      dtype='object')

In [11]:
df.head()

,DT_GERACAO,HH_GERACAO,ANO_ELEICAO,SG_UF,CD_MUNICIPIO,NM_MUNICIPIO,NR_ZONA,NR_SECAO,NR_LOCAL_VOTACAO,NM_LOCAL_VOTACAO,...,CD_IDENTIDADE_GENERO,DS_IDENTIDADE_GENERO,CD_QUILOMBOLA,DS_QUILOMBOLA,CD_INTERPRETE_LIBRAS,DS_INTERPRETE_LIBRAS,QT_ELEITORES_PERFIL,QT_ELEITORES_BIOMETRIA,QT_ELEITORES_DEFICIENCIA,QT_ELEITORES_INC_NM_SOCIAL
0,05/05/2025,11:10:05,9999,AM,2550,MANAUS,1,755,1996,IFAM - INST FED DE EDUCAÇÃO CIÊNCIA E TECNOLOG...,...,-1,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,1,1,0,0
1,05/05/2025,11:10:05,9999,AM,2550,MANAUS,1,755,1996,IFAM - INST FED DE EDUCAÇÃO CIÊNCIA E TECNOLOG...,...,-1,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,1,1,0,0
2,05/05/2025,11:10:05,9999,AM,2550,MANAUS,1,755,1996,IFAM - INST FED DE EDUCAÇÃO CIÊNCIA E TECNOLOG...,...,-1,NÃO INFORMADO,-1,NÃO INFORMADO,-1,NÃO INFORMADO,2,2,0,0
3,05/05/2025,11:10:05,9999,AM,2550,MANAUS,1,756,2380,E. E. SEN. CUNHA MELO,...,1,Cisgênero,2,NÃO,2,NÃO,1,1,0,0
4,05/05/2025,11:10:05,9999,AM,2550,MANAUS,1,756,2380,E. E. SEN. CUNHA MELO,...,1,Cisgênero,2,NÃO,2,NÃO,1,1,0,0

In [12]:
# Exemplo: Agrupar por ano e contar eleitores, assumindo uma coluna 'ano'
evolucao_por_ano = df.groupby('ANO_ELEICAO')['QT_ELEITORES_PERFIL'].sum() # ou a coluna que identifica o eleitor
print("Evolução do número de eleitores por ano:")
print(evolucao_por_ano)

Evolução do número de eleitores por ano:
ANO_ELEICAO
9999    2773831
Name: QT_ELEITORES_PERFIL, dtype: int64

#relacionar as características do eleitorado de acordo com o representante eleito em determinada região

In [13]:
import pandas as pd
from IPython import get_ipython
from IPython.display import display


try:
    df = pd.read_csv('/content/perfil_eleitor_secao_ATUAL_AM.csv',
                     sep=";", on_bad_lines = 'skip', encoding='Latin 1')

    df2 = pd.read_csv('/content/bweb_1t_AM_051020221321.csv',
                     sep=";", on_bad_lines = 'skip', encoding='Latin 1')

    zona_characteristics = df.groupby('NR_ZONA').agg(
        total_eleitores=('QT_ELEITORES_PERFIL', 'sum'),
        jovens=('DS_FAIXA_ETARIA', lambda x: (x.isin(['18 anos', '19 anos', '20 anos', '21 a 24 anos', '25 a 29 anos', '30 a 34 anos', '35 a 39 anos'])).sum()),
        idosos=('DS_FAIXA_ETARIA', lambda x: (x.isin(['60 a 64 anos', '65 a 69 anos', '70 a 74 anos', '75 a 79 anos', '80 a 84 anos', '85 a 89 anos', '90 a 94 anos', '95 a 99 anos', 'Superior a 100 anos'])).sum())
    ).reset_index()

    votacao_raw = {}
    for zona in df2.NR_ZONA.unique():
        result = df2.query('NR_ZONA == @zona').groupby('NM_VOTAVEL')['QT_VOTOS'].sum()
        total = sum(result)
        bolsonaro_votes = result.get("JAIR BOLSONARO", 0)
        lula_votes = result.get("LULA", 0)
        simone_votes = result.get('SIMONE TEBET', 0)
        nulo_votes = result.get('Nulo', 0)
        branco_votes = result.get('Branco', 0)

        votacao_raw[zona] = {
            'Jair Bolsonaro': round(bolsonaro_votes / total * 100, 1) if total > 0 else 0,
            'Lula': round(lula_votes / total * 100, 1) if total > 0 else 0,
            'Simone Tebet': round(simone_votes / total * 100, 1) if total > 0 else 0,
            'Nulos': round(nulo_votes / total * 100, 1) if total > 0 else 0,
            'Brancos': round(branco_votes / total * 100, 1) if total > 0 else 0
        }

    votacao = pd.DataFrame(votacao_raw).transpose().reset_index()
    votacao = votacao.rename(columns={'index': 'NR_ZONA'})

    merged_data = pd.merge(zona_characteristics, votacao, on='NR_ZONA')

    candidatos = ['Jair Bolsonaro', 'Lula', 'Simone Tebet']
    merged_data['Vencedor'] = merged_data[candidatos].idxmax(axis=1)

    print("Dados mesclados com o vencedor por zona:")
    display(merged_data.head())

except FileNotFoundError:
    print("Certifique-se de que os arquivos CSV estejam nos caminhos corretos.")
except KeyError as e:
    print(f"KeyError: {e}. Verifique se as colunas necessárias existem nos DataFrames.")
except Exception as e:
    print(f"Ocorreu um erro: {e}")

Dados mesclados com o vencedor por zona:

,NR_ZONA,total_eleitores,jovens,idosos,Jair Bolsonaro,Lula,Simone Tebet,Nulos,Brancos,Vencedor
0,1,99393,16162,15937,10.4,7.0,1.2,4.1,3.6,Jair Bolsonaro
1,2,92782,14788,11877,11.1,6.2,1.2,3.6,3.3,Jair Bolsonaro
2,3,89702,18180,10618,5.8,12.7,0.7,3.0,1.4,Lula
3,4,72943,13749,8244,2.9,15.7,0.7,2.8,2.0,Lula
4,5,51704,10999,5684,2.5,16.5,0.3,3.3,1.1,Lula

#Jornalista quer automatizar a exportação das estatísticas

In [14]:
FaixaEtaria.to_csv('FaixasIdade.csv')
estadocivil.to_csv('EstadoCivil.csv')
escolaridade.to_csv('Escolaridade.csv')